// ============================================================
// 人教版 (PEP) 小学英语 3-6 年级词汇库
// 三年级起点，共8册，约650+核心词汇
// 格式：{ english, chinese, grade, term, unit }
// ============================================================

const PEP_VOCABULARY = [
  // ==================== 三年级上册 ====================
  // U1 Hello!
  { e:"hello", c:"你好", g:3, t:"上", u:"Unit 1 Hello!" },
  { e:"hi", c:"嗨", g:3, t:"上", u:"Unit 1 Hello!" },
  { e:"goodbye", c:"再见", g:3, t:"上", u:"Unit 1 Hello!" },
  { e:"bye", c:"再见", g:3, t:"上", u:"Unit 1 Hello!" },
  { e:"I'm", c:"我是", g:3, t:"上", u:"Unit 1 Hello!" },
  { e:"my", c:"我的", g:3, t:"上", u:"Unit 1 Hello!" },
  { e:"name", c:"名字", g:3, t:"上", u:"Unit 1 Hello!" },
  { e:"what", c:"什么", g:3, t:"上", u:"Unit 1 Hello!" },
  { e:"your", c:"你的", g:3, t:"上", u:"Unit 1 Hello!" },
  { e:"ruler", c:"尺子", g:3, t:"上", u:"Unit 1 Hello!" },
  { e:"pencil", c:"铅笔", g:3, t:"上", u:"Unit 1 Hello!" },
  { e:"eraser", c:"橡皮", g:3, t:"上", u:"Unit 1 Hello!" },
  { e:"crayon", c:"蜡笔", g:3, t:"上", u:"Unit 1 Hello!" },
  { e:"bag", c:"书包", g:3, t:"上", u:"Unit 1 Hello!" },
  { e:"pen", c:"钢笔", g:3, t:"上", u:"Unit 1 Hello!" },
  { e:"book", c:"书", g:3, t:"上", u:"Unit 1 Hello!" },
  { e:"no", c:"不", g:3, t:"上", u:"Unit 1 Hello!" },

  // U2 Colours
  { e:"red", c:"红色", g:3, t:"上", u:"Unit 2 Colours" },
  { e:"green", c:"绿色", g:3, t:"上", u:"Unit 2 Colours" },
  { e:"yellow", c:"黄色", g:3, t:"上", u:"Unit 2 Colours" },
  { e:"blue", c:"蓝色", g:3, t:"上", u:"Unit 2 Colours" },
  { e:"black", c:"黑色", g:3, t:"上", u:"Unit 2 Colours" },
  { e:"white", c:"白色", g:3, t:"上", u:"Unit 2 Colours" },
  { e:"orange", c:"橙色", g:3, t:"上", u:"Unit 2 Colours" },
  { e:"brown", c:"棕色", g:3, t:"上", u:"Unit 2 Colours" },
  { e:"colour", c:"颜色", g:3, t:"上", u:"Unit 2 Colours" },
  { e:"OK", c:"好的", g:3, t:"上", u:"Unit 2 Colours" },
  { e:"mum", c:"妈妈", g:3, t:"上", u:"Unit 2 Colours" },

  // U3 Look at me!
  { e:"face", c:"脸", g:3, t:"上", u:"Unit 3 Look at me!" },
  { e:"ear", c:"耳朵", g:3, t:"上", u:"Unit 3 Look at me!" },
  { e:"eye", c:"眼睛", g:3, t:"上", u:"Unit 3 Look at me!" },
  { e:"nose", c:"鼻子", g:3, t:"上", u:"Unit 3 Look at me!" },
  { e:"mouth", c:"嘴", g:3, t:"上", u:"Unit 3 Look at me!" },
  { e:"arm", c:"胳膊", g:3, t:"上", u:"Unit 3 Look at me!" },
  { e:"hand", c:"手", g:3, t:"上", u:"Unit 3 Look at me!" },
  { e:"head", c:"头", g:3, t:"上", u:"Unit 3 Look at me!" },
  { e:"body", c:"身体", g:3, t:"上", u:"Unit 3 Look at me!" },
  { e:"leg", c:"腿", g:3, t:"上", u:"Unit 3 Look at me!" },
  { e:"foot", c:"脚", g:3, t:"上", u:"Unit 3 Look at me!" },
  { e:"school", c:"学校", g:3, t:"上", u:"Unit 3 Look at me!" },

  // U4 We love animals
  { e:"duck", c:"鸭子", g:3, t:"上", u:"Unit 4 We love animals" },
  { e:"pig", c:"猪", g:3, t:"上", u:"Unit 4 We love animals" },
  { e:"cat", c:"猫", g:3, t:"上", u:"Unit 4 We love animals" },
  { e:"bear", c:"熊", g:3, t:"上", u:"Unit 4 We love animals" },
  { e:"dog", c:"狗", g:3, t:"上", u:"Unit 4 We love animals" },
  { e:"elephant", c:"大象", g:3, t:"上", u:"Unit 4 We love animals" },
  { e:"monkey", c:"猴子", g:3, t:"上", u:"Unit 4 We love animals" },
  { e:"bird", c:"鸟", g:3, t:"上", u:"Unit 4 We love animals" },
  { e:"tiger", c:"老虎", g:3, t:"上", u:"Unit 4 We love animals" },
  { e:"panda", c:"熊猫", g:3, t:"上", u:"Unit 4 We love animals" },
  { e:"zoo", c:"动物园", g:3, t:"上", u:"Unit 4 We love animals" },
  { e:"funny", c:"滑稽的", g:3, t:"上", u:"Unit 4 We love animals" },

  // U5 Let's eat!
  { e:"bread", c:"面包", g:3, t:"上", u:"Unit 5 Let's eat!" },
  { e:"juice", c:"果汁", g:3, t:"上", u:"Unit 5 Let's eat!" },
  { e:"egg", c:"鸡蛋", g:3, t:"上", u:"Unit 5 Let's eat!" },
  { e:"milk", c:"牛奶", g:3, t:"上", u:"Unit 5 Let's eat!" },
  { e:"water", c:"水", g:3, t:"上", u:"Unit 5 Let's eat!" },
  { e:"cake", c:"蛋糕", g:3, t:"上", u:"Unit 5 Let's eat!" },
  { e:"fish", c:"鱼", g:3, t:"上", u:"Unit 5 Let's eat!" },
  { e:"rice", c:"米饭", g:3, t:"上", u:"Unit 5 Let's eat!" },
  { e:"eat", c:"吃", g:3, t:"上", u:"Unit 5 Let's eat!" },
  { e:"drink", c:"喝", g:3, t:"上", u:"Unit 5 Let's eat!" },

  // U6 Happy birthday!
  { e:"one", c:"一", g:3, t:"上", u:"Unit 6 Happy birthday!" },
  { e:"two", c:"二", g:3, t:"上", u:"Unit 6 Happy birthday!" },
  { e:"three", c:"三", g:3, t:"上", u:"Unit 6 Happy birthday!" },
  { e:"four", c:"四", g:3, t:"上", u:"Unit 6 Happy birthday!" },
  { e:"five", c:"五", g:3, t:"上", u:"Unit 6 Happy birthday!" },
  { e:"six", c:"六", g:3, t:"上", u:"Unit 6 Happy birthday!" },
  { e:"seven", c:"七", g:3, t:"上", u:"Unit 6 Happy birthday!" },
  { e:"eight", c:"八", g:3, t:"上", u:"Unit 6 Happy birthday!" },
  { e:"nine", c:"九", g:3, t:"上", u:"Unit 6 Happy birthday!" },
  { e:"ten", c:"十", g:3, t:"上", u:"Unit 6 Happy birthday!" },
  { e:"brother", c:"兄弟", g:3, t:"上", u:"Unit 6 Happy birthday!" },
  { e:"plate", c:"盘子", g:3, t:"上", u:"Unit 6 Happy birthday!" },
  { e:"old", c:"老的", g:3, t:"上", u:"Unit 6 Happy birthday!" },

  // ==================== 三年级下册 ====================
  // U1 Welcome back to school!
  { e:"UK", c:"英国", g:3, t:"下", u:"Unit 1 Welcome back" },
  { e:"Canada", c:"加拿大", g:3, t:"下", u:"Unit 1 Welcome back" },
  { e:"USA", c:"美国", g:3, t:"下", u:"Unit 1 Welcome back" },
  { e:"China", c:"中国", g:3, t:"下", u:"Unit 1 Welcome back" },
  { e:"she", c:"她", g:3, t:"下", u:"Unit 1 Welcome back" },
  { e:"he", c:"他", g:3, t:"下", u:"Unit 1 Welcome back" },
  { e:"student", c:"学生", g:3, t:"下", u:"Unit 1 Welcome back" },
  { e:"pupil", c:"小学生", g:3, t:"下", u:"Unit 1 Welcome back" },
  { e:"teacher", c:"老师", g:3, t:"下", u:"Unit 1 Welcome back" },
  { e:"boy", c:"男孩", g:3, t:"下", u:"Unit 1 Welcome back" },
  { e:"girl", c:"女孩", g:3, t:"下", u:"Unit 1 Welcome back" },
  { e:"new", c:"新的", g:3, t:"下", u:"Unit 1 Welcome back" },
  { e:"friend", c:"朋友", g:3, t:"下", u:"Unit 1 Welcome back" },
  { e:"today", c:"今天", g:3, t:"下", u:"Unit 1 Welcome back" },

  // U2 My family
  { e:"father", c:"父亲", g:3, t:"下", u:"Unit 2 My family" },
  { e:"dad", c:"爸爸", g:3, t:"下", u:"Unit 2 My family" },
  { e:"mother", c:"母亲", g:3, t:"下", u:"Unit 2 My family" },
  { e:"man", c:"男人", g:3, t:"下", u:"Unit 2 My family" },
  { e:"woman", c:"女人", g:3, t:"下", u:"Unit 2 My family" },
  { e:"grandfather", c:"爷爷/外公", g:3, t:"下", u:"Unit 2 My family" },
  { e:"grandmother", c:"奶奶/外婆", g:3, t:"下", u:"Unit 2 My family" },
  { e:"sister", c:"姐妹", g:3, t:"下", u:"Unit 2 My family" },
  { e:"family", c:"家庭", g:3, t:"下", u:"Unit 2 My family" },
  { e:"beautiful", c:"美丽的", g:3, t:"下", u:"Unit 2 My family" },

  // U3 At the zoo
  { e:"thin", c:"瘦的", g:3, t:"下", u:"Unit 3 At the zoo" },
  { e:"fat", c:"胖的", g:3, t:"下", u:"Unit 3 At the zoo" },
  { e:"tall", c:"高的", g:3, t:"下", u:"Unit 3 At the zoo" },
  { e:"short", c:"矮的", g:3, t:"下", u:"Unit 3 At the zoo" },
  { e:"long", c:"长的", g:3, t:"下", u:"Unit 3 At the zoo" },
  { e:"small", c:"小的", g:3, t:"下", u:"Unit 3 At the zoo" },
  { e:"big", c:"大的", g:3, t:"下", u:"Unit 3 At the zoo" },
  { e:"giraffe", c:"长颈鹿", g:3, t:"下", u:"Unit 3 At the zoo" },
  { e:"tail", c:"尾巴", g:3, t:"下", u:"Unit 3 At the zoo" },
  { e:"children", c:"孩子们", g:3, t:"下", u:"Unit 3 At the zoo" },

  // U4 Where is my car?
  { e:"on", c:"在...上", g:3, t:"下", u:"Unit 4 Where is my car?" },
  { e:"in", c:"在...里", g:3, t:"下", u:"Unit 4 Where is my car?" },
  { e:"under", c:"在...下", g:3, t:"下", u:"Unit 4 Where is my car?" },
  { e:"chair", c:"椅子", g:3, t:"下", u:"Unit 4 Where is my car?" },
  { e:"desk", c:"书桌", g:3, t:"下", u:"Unit 4 Where is my car?" },
  { e:"cap", c:"帽子", g:3, t:"下", u:"Unit 4 Where is my car?" },
  { e:"ball", c:"球", g:3, t:"下", u:"Unit 4 Where is my car?" },
  { e:"car", c:"汽车", g:3, t:"下", u:"Unit 4 Where is my car?" },
  { e:"boat", c:"小船", g:3, t:"下", u:"Unit 4 Where is my car?" },
  { e:"map", c:"地图", g:3, t:"下", u:"Unit 4 Where is my car?" },
  { e:"toy", c:"玩具", g:3, t:"下", u:"Unit 4 Where is my car?" },
  { e:"box", c:"盒子", g:3, t:"下", u:"Unit 4 Where is my car?" },

  // U5 Do you like pears?
  { e:"pear", c:"梨", g:3, t:"下", u:"Unit 5 Do you like pears?" },
  { e:"apple", c:"苹果", g:3, t:"下", u:"Unit 5 Do you like pears?" },
  { e:"banana", c:"香蕉", g:3, t:"下", u:"Unit 5 Do you like pears?" },
  { e:"watermelon", c:"西瓜", g:3, t:"下", u:"Unit 5 Do you like pears?" },
  { e:"strawberry", c:"草莓", g:3, t:"下", u:"Unit 5 Do you like pears?" },
  { e:"grape", c:"葡萄", g:3, t:"下", u:"Unit 5 Do you like pears?" },
  { e:"fruit", c:"水果", g:3, t:"下", u:"Unit 5 Do you like pears?" },
  { e:"buy", c:"买", g:3, t:"下", u:"Unit 5 Do you like pears?" },
  { e:"like", c:"喜欢", g:3, t:"下", u:"Unit 5 Do you like pears?" },

  // U6 How many?
  { e:"eleven", c:"十一", g:3, t:"下", u:"Unit 6 How many?" },
  { e:"twelve", c:"十二", g:3, t:"下", u:"Unit 6 How many?" },
  { e:"thirteen", c:"十三", g:3, t:"下", u:"Unit 6 How many?" },
  { e:"fourteen", c:"十四", g:3, t:"下", u:"Unit 6 How many?" },
  { e:"fifteen", c:"十五", g:3, t:"下", u:"Unit 6 How many?" },
  { e:"sixteen", c:"十六", g:3, t:"下", u:"Unit 6 How many?" },
  { e:"seventeen", c:"十七", g:3, t:"下", u:"Unit 6 How many?" },
  { e:"eighteen", c:"十八", g:3, t:"下", u:"Unit 6 How many?" },
  { e:"nineteen", c:"十九", g:3, t:"下", u:"Unit 6 How many?" },
  { e:"twenty", c:"二十", g:3, t:"下", u:"Unit 6 How many?" },
  { e:"kite", c:"风筝", g:3, t:"下", u:"Unit 6 How many?" },

  // ==================== 四年级上册 ====================
  // U1 My classroom
  { e:"classroom", c:"教室", g:4, t:"上", u:"Unit 1 My classroom" },
  { e:"window", c:"窗户", g:4, t:"上", u:"Unit 1 My classroom" },
  { e:"door", c:"门", g:4, t:"上", u:"Unit 1 My classroom" },
  { e:"picture", c:"图画", g:4, t:"上", u:"Unit 1 My classroom" },
  { e:"board", c:"黑板", g:4, t:"上", u:"Unit 1 My classroom" },
  { e:"light", c:"灯", g:4, t:"上", u:"Unit 1 My classroom" },
  { e:"wall", c:"墙", g:4, t:"上", u:"Unit 1 My classroom" },
  { e:"floor", c:"地板", g:4, t:"上", u:"Unit 1 My classroom" },
  { e:"computer", c:"电脑", g:4, t:"上", u:"Unit 1 My classroom" },
  { e:"fan", c:"风扇", g:4, t:"上", u:"Unit 1 My classroom" },
  { e:"clean", c:"打扫", g:4, t:"上", u:"Unit 1 My classroom" },
  { e:"near", c:"在...旁边", g:4, t:"上", u:"Unit 1 My classroom" },

  // U2 My schoolbag
  { e:"schoolbag", c:"书包", g:4, t:"上", u:"Unit 2 My schoolbag" },
  { e:"maths", c:"数学", g:4, t:"上", u:"Unit 2 My schoolbag" },
  { e:"English", c:"英语", g:4, t:"上", u:"Unit 2 My schoolbag" },
  { e:"Chinese", c:"语文", g:4, t:"上", u:"Unit 2 My schoolbag" },
  { e:"storybook", c:"故事书", g:4, t:"上", u:"Unit 2 My schoolbag" },
  { e:"notebook", c:"笔记本", g:4, t:"上", u:"Unit 2 My schoolbag" },
  { e:"key", c:"钥匙", g:4, t:"上", u:"Unit 2 My schoolbag" },
  { e:"wow", c:"哇", g:4, t:"上", u:"Unit 2 My schoolbag" },
  { e:"lost", c:"丢失", g:4, t:"上", u:"Unit 2 My schoolbag" },
  { e:"candy", c:"糖果", g:4, t:"上", u:"Unit 2 My schoolbag" },
  { e:"toy", c:"玩具", g:4, t:"上", u:"Unit 2 My schoolbag" },

  // U3 My friends
  { e:"strong", c:"强壮的", g:4, t:"上", u:"Unit 3 My friends" },
  { e:"friendly", c:"友好的", g:4, t:"上", u:"Unit 3 My friends" },
  { e:"quiet", c:"安静的", g:4, t:"上", u:"Unit 3 My friends" },
  { e:"hair", c:"头发", g:4, t:"上", u:"Unit 3 My friends" },
  { e:"shoe", c:"鞋", g:4, t:"上", u:"Unit 3 My friends" },
  { e:"glasses", c:"眼镜", g:4, t:"上", u:"Unit 3 My friends" },
  { e:"right", c:"正确的/右边", g:4, t:"上", u:"Unit 3 My friends" },
  { e:"hat", c:"帽子", g:4, t:"上", u:"Unit 3 My friends" },
  { e:"his", c:"他的", g:4, t:"上", u:"Unit 3 My friends" },
  { e:"her", c:"她的", g:4, t:"上", u:"Unit 3 My friends" },

  // U4 My home
  { e:"bedroom", c:"卧室", g:4, t:"上", u:"Unit 4 My home" },
  { e:"living room", c:"客厅", g:4, t:"上", u:"Unit 4 My home" },
  { e:"study", c:"书房", g:4, t:"上", u:"Unit 4 My home" },
  { e:"kitchen", c:"厨房", g:4, t:"上", u:"Unit 4 My home" },
  { e:"bathroom", c:"浴室", g:4, t:"上", u:"Unit 4 My home" },
  { e:"bed", c:"床", g:4, t:"上", u:"Unit 4 My home" },
  { e:"phone", c:"电话", g:4, t:"上", u:"Unit 4 My home" },
  { e:"table", c:"桌子", g:4, t:"上", u:"Unit 4 My home" },
  { e:"sofa", c:"沙发", g:4, t:"上", u:"Unit 4 My home" },
  { e:"fridge", c:"冰箱", g:4, t:"上", u:"Unit 4 My home" },
  { e:"find", c:"找到", g:4, t:"上", u:"Unit 4 My home" },

  // U5 Dinner's ready
  { e:"beef", c:"牛肉", g:4, t:"上", u:"Unit 5 Dinner's ready" },
  { e:"chicken", c:"鸡肉", g:4, t:"上", u:"Unit 5 Dinner's ready" },
  { e:"noodles", c:"面条", g:4, t:"上", u:"Unit 5 Dinner's ready" },
  { e:"soup", c:"汤", g:4, t:"上", u:"Unit 5 Dinner's ready" },
  { e:"vegetable", c:"蔬菜", g:4, t:"上", u:"Unit 5 Dinner's ready" },
  { e:"chopsticks", c:"筷子", g:4, t:"上", u:"Unit 5 Dinner's ready" },
  { e:"bowl", c:"碗", g:4, t:"上", u:"Unit 5 Dinner's ready" },
  { e:"fork", c:"叉子", g:4, t:"上", u:"Unit 5 Dinner's ready" },
  { e:"knife", c:"刀", g:4, t:"上", u:"Unit 5 Dinner's ready" },
  { e:"spoon", c:"勺子", g:4, t:"上", u:"Unit 5 Dinner's ready" },
  { e:"dinner", c:"晚餐", g:4, t:"上", u:"Unit 5 Dinner's ready" },
  { e:"ready", c:"准备好", g:4, t:"上", u:"Unit 5 Dinner's ready" },
  { e:"pass", c:"传递", g:4, t:"上", u:"Unit 5 Dinner's ready" },

  // U6 Meet my family!
  { e:"parents", c:"父母", g:4, t:"上", u:"Unit 6 Meet my family!" },
  { e:"cousin", c:"表兄弟姐妹", g:4, t:"上", u:"Unit 6 Meet my family!" },
  { e:"uncle", c:"叔叔/舅舅", g:4, t:"上", u:"Unit 6 Meet my family!" },
  { e:"aunt", c:"阿姨/姑姑", g:4, t:"上", u:"Unit 6 Meet my family!" },
  { e:"baby", c:"婴儿", g:4, t:"上", u:"Unit 6 Meet my family!" },
  { e:"doctor", c:"医生", g:4, t:"上", u:"Unit 6 Meet my family!" },
  { e:"cook", c:"厨师", g:4, t:"上", u:"Unit 6 Meet my family!" },
  { e:"driver", c:"司机", g:4, t:"上", u:"Unit 6 Meet my family!" },
  { e:"farmer", c:"农民", g:4, t:"上", u:"Unit 6 Meet my family!" },
  { e:"nurse", c:"护士", g:4, t:"上", u:"Unit 6 Meet my family!" },
  { e:"people", c:"人们", g:4, t:"上", u:"Unit 6 Meet my family!" },
  { e:"job", c:"工作", g:4, t:"上", u:"Unit 6 Meet my family!" },
  { e:"football", c:"足球", g:4, t:"上", u:"Unit 6 Meet my family!" },
  { e:"basketball", c:"篮球", g:4, t:"上", u:"Unit 6 Meet my family!" },

  // ==================== 四年级下册 ====================
  // U1 My school
  { e:"playground", c:"操场", g:4, t:"下", u:"Unit 1 My school" },
  { e:"garden", c:"花园", g:4, t:"下", u:"Unit 1 My school" },
  { e:"library", c:"图书馆", g:4, t:"下", u:"Unit 1 My school" },
  { e:"office", c:"办公室", g:4, t:"下", u:"Unit 1 My school" },
  { e:"homework", c:"作业", g:4, t:"下", u:"Unit 1 My school" },
  { e:"next to", c:"紧邻", g:4, t:"下", u:"Unit 1 My school" },
  { e:"second", c:"第二", g:4, t:"下", u:"Unit 1 My school" },
  { e:"floor", c:"楼层", g:4, t:"下", u:"Unit 1 My school" },
  { e:"way", c:"方向", g:4, t:"下", u:"Unit 1 My school" },
  { e:"forty", c:"四十", g:4, t:"下", u:"Unit 1 My school" },

  // U2 What time is it?
  { e:"breakfast", c:"早餐", g:4, t:"下", u:"Unit 2 What time is it?" },
  { e:"lunch", c:"午餐", g:4, t:"下", u:"Unit 2 What time is it?" },
  { e:"dinner", c:"晚餐", g:4, t:"下", u:"Unit 2 What time is it?" },
  { e:"class", c:"课", g:4, t:"下", u:"Unit 2 What time is it?" },
  { e:"music", c:"音乐", g:4, t:"下", u:"Unit 2 What time is it?" },
  { e:"PE", c:"体育", g:4, t:"下", u:"Unit 2 What time is it?" },
  { e:"get up", c:"起床", g:4, t:"下", u:"Unit 2 What time is it?" },
  { e:"go to school", c:"上学", g:4, t:"下", u:"Unit 2 What time is it?" },
  { e:"go home", c:"回家", g:4, t:"下", u:"Unit 2 What time is it?" },
  { e:"go to bed", c:"上床睡觉", g:4, t:"下", u:"Unit 2 What time is it?" },
  { e:"over", c:"结束", g:4, t:"下", u:"Unit 2 What time is it?" },
  { e:"now", c:"现在", g:4, t:"下", u:"Unit 2 What time is it?" },
  { e:"o'clock", c:"...点钟", g:4, t:"下", u:"Unit 2 What time is it?" },
  { e:"thirty", c:"三十", g:4, t:"下", u:"Unit 2 What time is it?" },

  // U3 Weather
  { e:"cold", c:"冷的", g:4, t:"下", u:"Unit 3 Weather" },
  { e:"cool", c:"凉爽的", g:4, t:"下", u:"Unit 3 Weather" },
  { e:"warm", c:"温暖的", g:4, t:"下", u:"Unit 3 Weather" },
  { e:"hot", c:"热的", g:4, t:"下", u:"Unit 3 Weather" },
  { e:"sunny", c:"晴朗的", g:4, t:"下", u:"Unit 3 Weather" },
  { e:"windy", c:"有风的", g:4, t:"下", u:"Unit 3 Weather" },
  { e:"cloudy", c:"多云的", g:4, t:"下", u:"Unit 3 Weather" },
  { e:"snowy", c:"下雪的", g:4, t:"下", u:"Unit 3 Weather" },
  { e:"rainy", c:"下雨的", g:4, t:"下", u:"Unit 3 Weather" },
  { e:"weather", c:"天气", g:4, t:"下", u:"Unit 3 Weather" },
  { e:"outside", c:"外面", g:4, t:"下", u:"Unit 3 Weather" },
  { e:"degree", c:"度", g:4, t:"下", u:"Unit 3 Weather" },
  { e:"world", c:"世界", g:4, t:"下", u:"Unit 3 Weather" },
  { e:"London", c:"伦敦", g:4, t:"下", u:"Unit 3 Weather" },
  { e:"Moscow", c:"莫斯科", g:4, t:"下", u:"Unit 3 Weather" },
  { e:"Sydney", c:"悉尼", g:4, t:"下", u:"Unit 3 Weather" },

  // U4 At the farm
  { e:"tomato", c:"西红柿", g:4, t:"下", u:"Unit 4 At the farm" },
  { e:"potato", c:"土豆", g:4, t:"下", u:"Unit 4 At the farm" },
  { e:"carrot", c:"胡萝卜", g:4, t:"下", u:"Unit 4 At the farm" },
  { e:"horse", c:"马", g:4, t:"下", u:"Unit 4 At the farm" },
  { e:"cow", c:"奶牛", g:4, t:"下", u:"Unit 4 At the farm" },
  { e:"sheep", c:"绵羊", g:4, t:"下", u:"Unit 4 At the farm" },
  { e:"hen", c:"母鸡", g:4, t:"下", u:"Unit 4 At the farm" },
  { e:"animal", c:"动物", g:4, t:"下", u:"Unit 4 At the farm" },
  { e:"farm", c:"农场", g:4, t:"下", u:"Unit 4 At the farm" },
  { e:"goat", c:"山羊", g:4, t:"下", u:"Unit 4 At the farm" },
  { e:"these", c:"这些", g:4, t:"下", u:"Unit 4 At the farm" },
  { e:"those", c:"那些", g:4, t:"下", u:"Unit 4 At the farm" },
  { e:"garden", c:"菜园", g:4, t:"下", u:"Unit 4 At the farm" },

  // U5 My clothes
  { e:"clothes", c:"衣服", g:4, t:"下", u:"Unit 5 My clothes" },
  { e:"pants", c:"裤子", g:4, t:"下", u:"Unit 5 My clothes" },
  { e:"hat", c:"帽子", g:4, t:"下", u:"Unit 5 My clothes" },
  { e:"dress", c:"连衣裙", g:4, t:"下", u:"Unit 5 My clothes" },
  { e:"skirt", c:"短裙", g:4, t:"下", u:"Unit 5 My clothes" },
  { e:"coat", c:"外套", g:4, t:"下", u:"Unit 5 My clothes" },
  { e:"sweater", c:"毛衣", g:4, t:"下", u:"Unit 5 My clothes" },
  { e:"sock", c:"袜子", g:4, t:"下", u:"Unit 5 My clothes" },
  { e:"shorts", c:"短裤", g:4, t:"下", u:"Unit 5 My clothes" },
  { e:"jacket", c:"夹克", g:4, t:"下", u:"Unit 5 My clothes" },
  { e:"shirt", c:"衬衫", g:4, t:"下", u:"Unit 5 My clothes" },
  { e:"yours", c:"你的(东西)", g:4, t:"下", u:"Unit 5 My clothes" },
  { e:"mine", c:"我的(东西)", g:4, t:"下", u:"Unit 5 My clothes" },
  { e:"pack", c:"收拾", g:4, t:"下", u:"Unit 5 My clothes" },
  { e:"wait", c:"等待", g:4, t:"下", u:"Unit 5 My clothes" },

  // U6 Shopping
  { e:"glove", c:"手套", g:4, t:"下", u:"Unit 6 Shopping" },
  { e:"scarf", c:"围巾", g:4, t:"下", u:"Unit 6 Shopping" },
  { e:"umbrella", c:"雨伞", g:4, t:"下", u:"Unit 6 Shopping" },
  { e:"sunglasses", c:"太阳镜", g:4, t:"下", u:"Unit 6 Shopping" },
  { e:"pretty", c:"漂亮的", g:4, t:"下", u:"Unit 6 Shopping" },
  { e:"expensive", c:"昂贵的", g:4, t:"下", u:"Unit 6 Shopping" },
  { e:"cheap", c:"便宜的", g:4, t:"下", u:"Unit 6 Shopping" },
  { e:"nice", c:"好的", g:4, t:"下", u:"Unit 6 Shopping" },
  { e:"try on", c:"试穿", g:4, t:"下", u:"Unit 6 Shopping" },
  { e:"size", c:"尺码", g:4, t:"下", u:"Unit 6 Shopping" },
  { e:"too", c:"太", g:4, t:"下", u:"Unit 6 Shopping" },
  { e:"just", c:"正好", g:4, t:"下", u:"Unit 6 Shopping" },
  { e:"dollar", c:"美元", g:4, t:"下", u:"Unit 6 Shopping" },
  { e:"how much", c:"多少钱", g:4, t:"下", u:"Unit 6 Shopping" },

  // ==================== 五年级上册 ====================
  // U1 What's he like?
  { e:"old", c:"老的", g:5, t:"上", u:"Unit 1 What's he like?" },
  { e:"young", c:"年轻的", g:5, t:"上", u:"Unit 1 What's he like?" },
  { e:"funny", c:"有趣的", g:5, t:"上", u:"Unit 1 What's he like?" },
  { e:"kind", c:"和蔼的", g:5, t:"上", u:"Unit 1 What's he like?" },
  { e:"strict", c:"严格的", g:5, t:"上", u:"Unit 1 What's he like?" },
  { e:"polite", c:"有礼貌的", g:5, t:"上", u:"Unit 1 What's he like?" },
  { e:"hard-working", c:"努力的", g:5, t:"上", u:"Unit 1 What's he like?" },
  { e:"helpful", c:"有帮助的", g:5, t:"上", u:"Unit 1 What's he like?" },
  { e:"clever", c:"聪明的", g:5, t:"上", u:"Unit 1 What's he like?" },
  { e:"shy", c:"害羞的", g:5, t:"上", u:"Unit 1 What's he like?" },
  { e:"know", c:"知道", g:5, t:"上", u:"Unit 1 What's he like?" },
  { e:"speak", c:"说", g:5, t:"上", u:"Unit 1 What's he like?" },
  { e:"finish", c:"完成", g:5, t:"上", u:"Unit 1 What's he like?" },
  { e:"sometimes", c:"有时", g:5, t:"上", u:"Unit 1 What's he like?" },

  // U2 My week
  { e:"Monday", c:"星期一", g:5, t:"上", u:"Unit 2 My week" },
  { e:"Tuesday", c:"星期二", g:5, t:"上", u:"Unit 2 My week" },
  { e:"Wednesday", c:"星期三", g:5, t:"上", u:"Unit 2 My week" },
  { e:"Thursday", c:"星期四", g:5, t:"上", u:"Unit 2 My week" },
  { e:"Friday", c:"星期五", g:5, t:"上", u:"Unit 2 My week" },
  { e:"Saturday", c:"星期六", g:5, t:"上", u:"Unit 2 My week" },
  { e:"Sunday", c:"星期日", g:5, t:"上", u:"Unit 2 My week" },
  { e:"weekend", c:"周末", g:5, t:"上", u:"Unit 2 My week" },
  { e:"wash", c:"洗", g:5, t:"上", u:"Unit 2 My week" },
  { e:"watch", c:"看", g:5, t:"上", u:"Unit 2 My week" },
  { e:"read", c:"阅读", g:5, t:"上", u:"Unit 2 My week" },
  { e:"play", c:"玩", g:5, t:"上", u:"Unit 2 My week" },
  { e:"do", c:"做", g:5, t:"上", u:"Unit 2 My week" },
  { e:"often", c:"经常", g:5, t:"上", u:"Unit 2 My week" },
  { e:"park", c:"公园", g:5, t:"上", u:"Unit 2 My week" },
  { e:"tired", c:"累的", g:5, t:"上", u:"Unit 2 My week" },
  { e:"sport", c:"运动", g:5, t:"上", u:"Unit 2 My week" },
  { e:"should", c:"应该", g:5, t:"上", u:"Unit 2 My week" },
  { e:"every", c:"每个", g:5, t:"上", u:"Unit 2 My week" },
  { e:"schedule", c:"时间表", g:5, t:"上", u:"Unit 2 My week" },

  // U3 What would you like?
  { e:"sandwich", c:"三明治", g:5, t:"上", u:"Unit 3 What would you like?" },
  { e:"salad", c:"沙拉", g:5, t:"上", u:"Unit 3 What would you like?" },
  { e:"hamburger", c:"汉堡包", g:5, t:"上", u:"Unit 3 What would you like?" },
  { e:"ice cream", c:"冰淇淋", g:5, t:"上", u:"Unit 3 What would you like?" },
  { e:"tea", c:"茶", g:5, t:"上", u:"Unit 3 What would you like?" },
  { e:"fresh", c:"新鲜的", g:5, t:"上", u:"Unit 3 What would you like?" },
  { e:"healthy", c:"健康的", g:5, t:"上", u:"Unit 3 What would you like?" },
  { e:"delicious", c:"美味的", g:5, t:"上", u:"Unit 3 What would you like?" },
  { e:"hot", c:"辣的", g:5, t:"上", u:"Unit 3 What would you like?" },
  { e:"sweet", c:"甜的", g:5, t:"上", u:"Unit 3 What would you like?" },
  { e:"favourite", c:"最喜欢的", g:5, t:"上", u:"Unit 3 What would you like?" },
  { e:"food", c:"食物", g:5, t:"上", u:"Unit 3 What would you like?" },
  { e:"onion", c:"洋葱", g:5, t:"上", u:"Unit 3 What would you like?" },

  // U4 What can you do?
  { e:"sing", c:"唱歌", g:5, t:"上", u:"Unit 4 What can you do?" },
  { e:"dance", c:"跳舞", g:5, t:"上", u:"Unit 4 What can you do?" },
  { e:"draw", c:"画画", g:5, t:"上", u:"Unit 4 What can you do?" },
  { e:"cartoon", c:"卡通", g:5, t:"上", u:"Unit 4 What can you do?" },
  { e:"cook", c:"烹饪", g:5, t:"上", u:"Unit 4 What can you do?" },
  { e:"swim", c:"游泳", g:5, t:"上", u:"Unit 4 What can you do?" },
  { e:"basketball", c:"篮球", g:5, t:"上", u:"Unit 4 What can you do?" },
  { e:"ping-pong", c:"乒乓球", g:5, t:"上", u:"Unit 4 What can you do?" },
  { e:"speak English", c:"说英语", g:5, t:"上", u:"Unit 4 What can you do?" },
  { e:"party", c:"聚会", g:5, t:"上", u:"Unit 4 What can you do?" },
  { e:"next", c:"下一个", g:5, t:"上", u:"Unit 4 What can you do?" },
  { e:"wonderful", c:"精彩的", g:5, t:"上", u:"Unit 4 What can you do?" },
  { e:"learn", c:"学习", g:5, t:"上", u:"Unit 4 What can you do?" },
  { e:"any", c:"任何", g:5, t:"上", u:"Unit 4 What can you do?" },
  { e:"problem", c:"问题", g:5, t:"上", u:"Unit 4 What can you do?" },
  { e:"send", c:"发送", g:5, t:"上", u:"Unit 4 What can you do?" },

  // U5 There is a big bed
  { e:"clock", c:"时钟", g:5, t:"上", u:"Unit 5 There is a big bed" },
  { e:"plant", c:"植物", g:5, t:"上", u:"Unit 5 There is a big bed" },
  { e:"bottle", c:"瓶子", g:5, t:"上", u:"Unit 5 There is a big bed" },
  { e:"bike", c:"自行车", g:5, t:"上", u:"Unit 5 There is a big bed" },
  { e:"photo", c:"照片", g:5, t:"上", u:"Unit 5 There is a big bed" },
  { e:"front", c:"前面", g:5, t:"上", u:"Unit 5 There is a big bed" },
  { e:"between", c:"在...之间", g:5, t:"上", u:"Unit 5 There is a big bed" },
  { e:"above", c:"在...上面", g:5, t:"上", u:"Unit 5 There is a big bed" },
  { e:"beside", c:"在...旁边", g:5, t:"上", u:"Unit 5 There is a big bed" },
  { e:"behind", c:"在...后面", g:5, t:"上", u:"Unit 5 There is a big bed" },
  { e:"there", c:"那里", g:5, t:"上", u:"Unit 5 There is a big bed" },
  { e:"grandparent", c:"祖父母", g:5, t:"上", u:"Unit 5 There is a big bed" },
  { e:"their", c:"他们的", g:5, t:"上", u:"Unit 5 There is a big bed" },
  { e:"house", c:"房子", g:5, t:"上", u:"Unit 5 There is a big bed" },
  { e:"lots of", c:"许多", g:5, t:"上", u:"Unit 5 There is a big bed" },
  { e:"move", c:"搬动", g:5, t:"上", u:"Unit 5 There is a big bed" },
  { e:"nature", c:"自然", g:5, t:"上", u:"Unit 5 There is a big bed" },

  // U6 In a nature park
  { e:"forest", c:"森林", g:5, t:"上", u:"Unit 6 In a nature park" },
  { e:"lake", c:"湖", g:5, t:"上", u:"Unit 6 In a nature park" },
  { e:"river", c:"河流", g:5, t:"上", u:"Unit 6 In a nature park" },
  { e:"mountain", c:"山", g:5, t:"上", u:"Unit 6 In a nature park" },
  { e:"hill", c:"小山", g:5, t:"上", u:"Unit 6 In a nature park" },
  { e:"tree", c:"树", g:5, t:"上", u:"Unit 6 In a nature park" },
  { e:"bridge", c:"桥", g:5, t:"上", u:"Unit 6 In a nature park" },
  { e:"village", c:"村庄", g:5, t:"上", u:"Unit 6 In a nature park" },
  { e:"building", c:"建筑物", g:5, t:"上", u:"Unit 6 In a nature park" },
  { e:"house", c:"房子", g:5, t:"上", u:"Unit 6 In a nature park" },
  { e:"go boating", c:"划船", g:5, t:"上", u:"Unit 6 In a nature park" },
  { e:"rabbit", c:"兔子", g:5, t:"上", u:"Unit 6 In a nature park" },
  { e:"high", c:"高的", g:5, t:"上", u:"Unit 6 In a nature park" },

  // ==================== 五年级下册 ====================
  // U1 My day
  { e:"eat breakfast", c:"吃早饭", g:5, t:"下", u:"Unit 1 My day" },
  { e:"have class", c:"上课", g:5, t:"下", u:"Unit 1 My day" },
  { e:"play sports", c:"做运动", g:5, t:"下", u:"Unit 1 My day" },
  { e:"do morning exercises", c:"做早操", g:5, t:"下", u:"Unit 1 My day" },
  { e:"eat dinner", c:"吃晚饭", g:5, t:"下", u:"Unit 1 My day" },
  { e:"clean my room", c:"打扫房间", g:5, t:"下", u:"Unit 1 My day" },
  { e:"go shopping", c:"购物", g:5, t:"下", u:"Unit 1 My day" },
  { e:"take a dancing class", c:"上舞蹈课", g:5, t:"下", u:"Unit 1 My day" },
  { e:"usually", c:"通常", g:5, t:"下", u:"Unit 1 My day" },
  { e:"always", c:"总是", g:5, t:"下", u:"Unit 1 My day" },
  { e:"sometimes", c:"有时候", g:5, t:"下", u:"Unit 1 My day" },
  { e:"busy", c:"忙碌的", g:5, t:"下", u:"Unit 1 My day" },
  { e:"need", c:"需要", g:5, t:"下", u:"Unit 1 My day" },
  { e:"letter", c:"信", g:5, t:"下", u:"Unit 1 My day" },

  // U2 My favourite season
  { e:"spring", c:"春天", g:5, t:"下", u:"Unit 2 My favourite season" },
  { e:"summer", c:"夏天", g:5, t:"下", u:"Unit 2 My favourite season" },
  { e:"autumn", c:"秋天", g:5, t:"下", u:"Unit 2 My favourite season" },
  { e:"winter", c:"冬天", g:5, t:"下", u:"Unit 2 My favourite season" },
  { e:"season", c:"季节", g:5, t:"下", u:"Unit 2 My favourite season" },
  { e:"picnic", c:"野餐", g:5, t:"下", u:"Unit 2 My favourite season" },
  { e:"pick", c:"采摘", g:5, t:"下", u:"Unit 2 My favourite season" },
  { e:"snowman", c:"雪人", g:5, t:"下", u:"Unit 2 My favourite season" },
  { e:"go swimming", c:"去游泳", g:5, t:"下", u:"Unit 2 My favourite season" },
  { e:"vacation", c:"假期", g:5, t:"下", u:"Unit 2 My favourite season" },
  { e:"paint", c:"绘画", g:5, t:"下", u:"Unit 2 My favourite season" },
  { e:"because", c:"因为", g:5, t:"下", u:"Unit 2 My favourite season" },
  { e:"leaf", c:"叶子", g:5, t:"下", u:"Unit 2 My favourite season" },
  { e:"fall", c:"落下/秋天", g:5, t:"下", u:"Unit 2 My favourite season" },

  // U3 My school calendar
  { e:"January", c:"一月", g:5, t:"下", u:"Unit 3 My school calendar" },
  { e:"February", c:"二月", g:5, t:"下", u:"Unit 3 My school calendar" },
  { e:"March", c:"三月", g:5, t:"下", u:"Unit 3 My school calendar" },
  { e:"April", c:"四月", g:5, t:"下", u:"Unit 3 My school calendar" },
  { e:"May", c:"五月", g:5, t:"下", u:"Unit 3 My school calendar" },
  { e:"June", c:"六月", g:5, t:"下", u:"Unit 3 My school calendar" },
  { e:"July", c:"七月", g:5, t:"下", u:"Unit 3 My school calendar" },
  { e:"August", c:"八月", g:5, t:"下", u:"Unit 3 My school calendar" },
  { e:"September", c:"九月", g:5, t:"下", u:"Unit 3 My school calendar" },
  { e:"October", c:"十月", g:5, t:"下", u:"Unit 3 My school calendar" },
  { e:"November", c:"十一月", g:5, t:"下", u:"Unit 3 My school calendar" },
  { e:"December", c:"十二月", g:5, t:"下", u:"Unit 3 My school calendar" },
  { e:"plant", c:"种植", g:5, t:"下", u:"Unit 3 My school calendar" },
  { e:"contest", c:"比赛", g:5, t:"下", u:"Unit 3 My school calendar" },
  { e:"year", c:"年", g:5, t:"下", u:"Unit 3 My school calendar" },
  { e:"trip", c:"旅行", g:5, t:"下", u:"Unit 3 My school calendar" },
  { e:"national", c:"国家的", g:5, t:"下", u:"Unit 3 My school calendar" },

  // U4 When is Easter?
  { e:"first", c:"第一", g:5, t:"下", u:"Unit 4 When is Easter?" },
  { e:"second", c:"第二", g:5, t:"下", u:"Unit 4 When is Easter?" },
  { e:"third", c:"第三", g:5, t:"下", u:"Unit 4 When is Easter?" },
  { e:"fourth", c:"第四", g:5, t:"下", u:"Unit 4 When is Easter?" },
  { e:"fifth", c:"第五", g:5, t:"下", u:"Unit 4 When is Easter?" },
  { e:"twelfth", c:"第十二", g:5, t:"下", u:"Unit 4 When is Easter?" },
  { e:"twentieth", c:"第二十", g:5, t:"下", u:"Unit 4 When is Easter?" },
  { e:"special", c:"特别的", g:5, t:"下", u:"Unit 4 When is Easter?" },
  { e:"diary", c:"日记", g:5, t:"下", u:"Unit 4 When is Easter?" },
  { e:"still", c:"仍然", g:5, t:"下", u:"Unit 4 When is Easter?" },
  { e:"noise", c:"噪音", g:5, t:"下", u:"Unit 4 When is Easter?" },
  { e:"open", c:"打开", g:5, t:"下", u:"Unit 4 When is Easter?" },
  { e:"walk", c:"走路", g:5, t:"下", u:"Unit 4 When is Easter?" },

  // U5 Whose dog is it?
  { e:"mine", c:"我的", g:5, t:"下", u:"Unit 5 Whose dog is it?" },
  { e:"yours", c:"你的", g:5, t:"下", u:"Unit 5 Whose dog is it?" },
  { e:"his", c:"他的", g:5, t:"下", u:"Unit 5 Whose dog is it?" },
  { e:"hers", c:"她的", g:5, t:"下", u:"Unit 5 Whose dog is it?" },
  { e:"theirs", c:"他们的", g:5, t:"下", u:"Unit 5 Whose dog is it?" },
  { e:"ours", c:"我们的", g:5, t:"下", u:"Unit 5 Whose dog is it?" },
  { e:"climbing", c:"攀登", g:5, t:"下", u:"Unit 5 Whose dog is it?" },
  { e:"eating", c:"正在吃", g:5, t:"下", u:"Unit 5 Whose dog is it?" },
  { e:"playing", c:"正在玩", g:5, t:"下", u:"Unit 5 Whose dog is it?" },
  { e:"jumping", c:"跳", g:5, t:"下", u:"Unit 5 Whose dog is it?" },
  { e:"drinking", c:"正在喝", g:5, t:"下", u:"Unit 5 Whose dog is it?" },
  { e:"sleeping", c:"正在睡觉", g:5, t:"下", u:"Unit 5 Whose dog is it?" },
  { e:"each", c:"每个", g:5, t:"下", u:"Unit 5 Whose dog is it?" },
  { e:"excited", c:"兴奋的", g:5, t:"下", u:"Unit 5 Whose dog is it?" },

  // U6 Work quietly!
  { e:"doing morning exercises", c:"做早操", g:5, t:"下", u:"Unit 6 Work quietly!" },
  { e:"having class", c:"上课", g:5, t:"下", u:"Unit 6 Work quietly!" },
  { e:"eating lunch", c:"吃午餐", g:5, t:"下", u:"Unit 6 Work quietly!" },
  { e:"reading a book", c:"读书", g:5, t:"下", u:"Unit 6 Work quietly!" },
  { e:"listening to music", c:"听音乐", g:5, t:"下", u:"Unit 6 Work quietly!" },
  { e:"keep", c:"保持", g:5, t:"下", u:"Unit 6 Work quietly!" },
  { e:"turn", c:"转向", g:5, t:"下", u:"Unit 6 Work quietly!" },
  { e:"take turns", c:"轮流", g:5, t:"下", u:"Unit 6 Work quietly!" },
  { e:"bamboo", c:"竹子", g:5, t:"下", u:"Unit 6 Work quietly!" },
  { e:"its", c:"它的", g:5, t:"下", u:"Unit 6 Work quietly!" },
  { e:"show", c:"展示", g:5, t:"下", u:"Unit 6 Work quietly!" },
  { e:"anything", c:"任何东西", g:5, t:"下", u:"Unit 6 Work quietly!" },
  { e:"else", c:"其他的", g:5, t:"下", u:"Unit 6 Work quietly!" },
  { e:"say", c:"说", g:5, t:"下", u:"Unit 6 Work quietly!" },

  // ==================== 六年级上册 ====================
  // U1 How can I get there?
  { e:"science", c:"科学", g:6, t:"上", u:"Unit 1 How can I get there?" },
  { e:"museum", c:"博物馆", g:6, t:"上", u:"Unit 1 How can I get there?" },
  { e:"post office", c:"邮局", g:6, t:"上", u:"Unit 1 How can I get there?" },
  { e:"bookstore", c:"书店", g:6, t:"上", u:"Unit 1 How can I get there?" },
  { e:"cinema", c:"电影院", g:6, t:"上", u:"Unit 1 How can I get there?" },
  { e:"hospital", c:"医院", g:6, t:"上", u:"Unit 1 How can I get there?" },
  { e:"crossing", c:"十字路口", g:6, t:"上", u:"Unit 1 How can I get there?" },
  { e:"turn left", c:"左转", g:6, t:"上", u:"Unit 1 How can I get there?" },
  { e:"turn right", c:"右转", g:6, t:"上", u:"Unit 1 How can I get there?" },
  { e:"go straight", c:"直走", g:6, t:"上", u:"Unit 1 How can I get there?" },
  { e:"street", c:"街道", g:6, t:"上", u:"Unit 1 How can I get there?" },
  { e:"GPS", c:"导航", g:6, t:"上", u:"Unit 1 How can I get there?" },
  { e:"feature", c:"特点", g:6, t:"上", u:"Unit 1 How can I get there?" },
  { e:"far", c:"远的", g:6, t:"上", u:"Unit 1 How can I get there?" },

  // U2 Ways to go to school
  { e:"on foot", c:"步行", g:6, t:"上", u:"Unit 2 Ways to go to school" },
  { e:"by bus", c:"乘公交", g:6, t:"上", u:"Unit 2 Ways to go to school" },
  { e:"by bike", c:"骑自行车", g:6, t:"上", u:"Unit 2 Ways to go to school" },
  { e:"by taxi", c:"乘出租车", g:6, t:"上", u:"Unit 2 Ways to go to school" },
  { e:"by subway", c:"乘地铁", g:6, t:"上", u:"Unit 2 Ways to go to school" },
  { e:"by plane", c:"乘飞机", g:6, t:"上", u:"Unit 2 Ways to go to school" },
  { e:"by train", c:"乘火车", g:6, t:"上", u:"Unit 2 Ways to go to school" },
  { e:"by ship", c:"乘船", g:6, t:"上", u:"Unit 2 Ways to go to school" },
  { e:"slow", c:"慢的", g:6, t:"上", u:"Unit 2 Ways to go to school" },
  { e:"fast", c:"快的", g:6, t:"上", u:"Unit 2 Ways to go to school" },
  { e:"must", c:"必须", g:6, t:"上", u:"Unit 2 Ways to go to school" },
  { e:"wear", c:"穿/戴", g:6, t:"上", u:"Unit 2 Ways to go to school" },
  { e:"helmet", c:"头盔", g:6, t:"上", u:"Unit 2 Ways to go to school" },
  { e:"attention", c:"注意", g:6, t:"上", u:"Unit 2 Ways to go to school" },
  { e:"ferry", c:"轮渡", g:6, t:"上", u:"Unit 2 Ways to go to school" },

  // U3 My weekend plan
  { e:"visit", c:"拜访", g:6, t:"上", u:"Unit 3 My weekend plan" },
  { e:"film", c:"电影", g:6, t:"上", u:"Unit 3 My weekend plan" },
  { e:"trip", c:"旅行", g:6, t:"上", u:"Unit 3 My weekend plan" },
  { e:"supermarket", c:"超市", g:6, t:"上", u:"Unit 3 My weekend plan" },
  { e:"evening", c:"傍晚", g:6, t:"上", u:"Unit 3 My weekend plan" },
  { e:"tonight", c:"今晚", g:6, t:"上", u:"Unit 3 My weekend plan" },
  { e:"tomorrow", c:"明天", g:6, t:"上", u:"Unit 3 My weekend plan" },
  { e:"next week", c:"下周", g:6, t:"上", u:"Unit 3 My weekend plan" },
  { e:"dictionary", c:"字典", g:6, t:"上", u:"Unit 3 My weekend plan" },
  { e:"comic book", c:"漫画书", g:6, t:"上", u:"Unit 3 My weekend plan" },
  { e:"word book", c:"单词书", g:6, t:"上", u:"Unit 3 My weekend plan" },
  { e:"postcard", c:"明信片", g:6, t:"上", u:"Unit 3 My weekend plan" },
  { e:"lesson", c:"课", g:6, t:"上", u:"Unit 3 My weekend plan" },
  { e:"half", c:"一半", g:6, t:"上", u:"Unit 3 My weekend plan" },
  { e:"price", c:"价格", g:6, t:"上", u:"Unit 3 My weekend plan" },

  // U4 I have a pen pal
  { e:"pen pal", c:"笔友", g:6, t:"上", u:"Unit 4 I have a pen pal" },
  { e:"hobby", c:"爱好", g:6, t:"上", u:"Unit 4 I have a pen pal" },
  { e:"jasmine", c:"茉莉", g:6, t:"上", u:"Unit 4 I have a pen pal" },
  { e:"idea", c:"想法", g:6, t:"上", u:"Unit 4 I have a pen pal" },
  { e:"studies", c:"学习", g:6, t:"上", u:"Unit 4 I have a pen pal" },
  { e:"puzzle", c:"谜题", g:6, t:"上", u:"Unit 4 I have a pen pal" },
  { e:"hiking", c:"远足", g:6, t:"上", u:"Unit 4 I have a pen pal" },
  { e:"join", c:"加入", g:6, t:"上", u:"Unit 4 I have a pen pal" },
  { e:"club", c:"俱乐部", g:6, t:"上", u:"Unit 4 I have a pen pal" },
  { e:"share", c:"分享", g:6, t:"上", u:"Unit 4 I have a pen pal" },

  // U5 What does he do?
  { e:"factory", c:"工厂", g:6, t:"上", u:"Unit 5 What does he do?" },
  { e:"worker", c:"工人", g:6, t:"上", u:"Unit 5 What does he do?" },
  { e:"postman", c:"邮递员", g:6, t:"上", u:"Unit 5 What does he do?" },
  { e:"businessman", c:"商人", g:6, t:"上", u:"Unit 5 What does he do?" },
  { e:"police officer", c:"警察", g:6, t:"上", u:"Unit 5 What does he do?" },
  { e:"fisherman", c:"渔夫", g:6, t:"上", u:"Unit 5 What does he do?" },
  { e:"scientist", c:"科学家", g:6, t:"上", u:"Unit 5 What does he do?" },
  { e:"pilot", c:"飞行员", g:6, t:"上", u:"Unit 5 What does he do?" },
  { e:"coach", c:"教练", g:6, t:"上", u:"Unit 5 What does he do?" },
  { e:"head teacher", c:"校长", g:6, t:"上", u:"Unit 5 What does he do?" },
  { e:"reporter", c:"记者", g:6, t:"上", u:"Unit 5 What does he do?" },
  { e:"secretary", c:"秘书", g:6, t:"上", u:"Unit 5 What does he do?" },
  { e:"type", c:"打字", g:6, t:"上", u:"Unit 5 What does he do?" },
  { e:"quickly", c:"快速地", g:6, t:"上", u:"Unit 5 What does he do?" },
  { e:"stay", c:"保持", g:6, t:"上", u:"Unit 5 What does he do?" },

  // U6 How do you feel?
  { e:"angry", c:"生气的", g:6, t:"上", u:"Unit 6 How do you feel?" },
  { e:"afraid", c:"害怕的", g:6, t:"上", u:"Unit 6 How do you feel?" },
  { e:"sad", c:"难过的", g:6, t:"上", u:"Unit 6 How do you feel?" },
  { e:"worried", c:"担心的", g:6, t:"上", u:"Unit 6 How do you feel?" },
  { e:"happy", c:"开心的", g:6, t:"上", u:"Unit 6 How do you feel?" },
  { e:"ill", c:"生病的", g:6, t:"上", u:"Unit 6 How do you feel?" },
  { e:"wrong", c:"错误的", g:6, t:"上", u:"Unit 6 How do you feel?" },
  { e:"feel", c:"感觉", g:6, t:"上", u:"Unit 6 How do you feel?" },
  { e:"mice", c:"老鼠(复数)", g:6, t:"上", u:"Unit 6 How do you feel?" },
  { e:"bad", c:"坏的", g:6, t:"上", u:"Unit 6 How do you feel?" },
  { e:"hurt", c:"受伤", g:6, t:"上", u:"Unit 6 How do you feel?" },
  { e:"check", c:"检查", g:6, t:"上", u:"Unit 6 How do you feel?" },
  { e:"pull", c:"拉", g:6, t:"上", u:"Unit 6 How do you feel?" },
  { e:"everyone", c:"每个人", g:6, t:"上", u:"Unit 6 How do you feel?" },
  { e:"count", c:"数数", g:6, t:"上", u:"Unit 6 How do you feel?" },
  { e:"deep", c:"深的", g:6, t:"上", u:"Unit 6 How do you feel?" },
  { e:"breath", c:"呼吸", g:6, t:"上", u:"Unit 6 How do you feel?" },

  // ==================== 六年级下册 ====================
  // U1 How tall are you?
  { e:"younger", c:"更年轻的", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"older", c:"更年长的", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"taller", c:"更高的", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"shorter", c:"更矮的", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"longer", c:"更长的", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"thinner", c:"更瘦的", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"heavier", c:"更重的", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"bigger", c:"更大的", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"smaller", c:"更小的", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"stronger", c:"更强壮的", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"dinosaur", c:"恐龙", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"hall", c:"大厅", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"metre", c:"米", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"than", c:"比", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"both", c:"两者都", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"kilogram", c:"千克", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"countryside", c:"乡村", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"shadow", c:"影子", g:6, t:"下", u:"Unit 1 How tall are you?" },
  { e:"smarter", c:"更聪明的", g:6, t:"下", u:"Unit 1 How tall are you?" },

  // U2 Last weekend
  { e:"cleaned", c:"打扫了", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"stayed", c:"停留了", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"washed", c:"洗了", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"watched", c:"看了", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"had", c:"有/吃了", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"slept", c:"睡了", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"read", c:"读了", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"saw", c:"看见了", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"went", c:"去了", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"did", c:"做了", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"last", c:"上一个", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"yesterday", c:"昨天", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"before", c:"在...之前", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"drank", c:"喝了", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"show", c:"节目", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"magazine", c:"杂志", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"better", c:"更好的", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"faster", c:"更快的", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"hotel", c:"酒店", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"fixed", c:"修理了", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"broken", c:"坏的", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"lamp", c:"台灯", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"loud", c:"大声的", g:6, t:"下", u:"Unit 2 Last weekend" },
  { e:"enjoy", c:"享受", g:6, t:"下", u:"Unit 2 Last weekend" },

  // U3 Where did you go?
  { e:"went camping", c:"去野营", g:6, t:"下", u:"Unit 3 Where did you go?" },
  { e:"went fishing", c:"去钓鱼", g:6, t:"下", u:"Unit 3 Where did you go?" },
  { e:"rode a horse", c:"骑马", g:6, t:"下", u:"Unit 3 Where did you go?" },
  { e:"rode a bike", c:"骑自行车", g:6, t:"下", u:"Unit 3 Where did you go?" },
  { e:"hurt my foot", c:"伤到脚", g:6, t:"下", u:"Unit 3 Where did you go?" },
  { e:"ate fresh food", c:"吃新鲜食物", g:6, t:"下", u:"Unit 3 Where did you go?" },
  { e:"bought gifts", c:"买礼物", g:6, t:"下", u:"Unit 3 Where did you go?" },
  { e:"took pictures", c:"拍照", g:6, t:"下", u:"Unit 3 Where did you go?" },
  { e:"beach", c:"海滩", g:6, t:"下", u:"Unit 3 Where did you go?" },
  { e:"basket", c:"篮子", g:6, t:"下", u:"Unit 3 Where did you go?" },
  { e:"part", c:"部分", g:6, t:"下", u:"Unit 3 Where did you go?" },
  { e:"licked", c:"舔了", g:6, t:"下", u:"Unit 3 Where did you go?" },
  { e:"laughed", c:"笑了", g:6, t:"下", u:"Unit 3 Where did you go?" },

  // U4 Then and now
  { e:"dining hall", c:"餐厅", g:6, t:"下", u:"Unit 4 Then and now" },
  { e:"grass", c:"草坪", g:6, t:"下", u:"Unit 4 Then and now" },
  { e:"gym", c:"体育馆", g:6, t:"下", u:"Unit 4 Then and now" },
  { e:"ago", c:"以前", g:6, t:"下", u:"Unit 4 Then and now" },
  { e:"cycling", c:"骑自行车", g:6, t:"下", u:"Unit 4 Then and now" },
  { e:"badminton", c:"羽毛球", g:6, t:"下", u:"Unit 4 Then and now" },
  { e:"star", c:"星星", g:6, t:"下", u:"Unit 4 Then and now" },
  { e:"easy", c:"容易的", g:6, t:"下", u:"Unit 4 Then and now" },
  { e:"different", c:"不同的", g:6, t:"下", u:"Unit 4 Then and now" },
  { e:"active", c:"活跃的", g:6, t:"下", u:"Unit 4 Then and now" },
  { e:"race", c:"赛跑", g:6, t:"下", u:"Unit 4 Then and now" },
  { e:"nothing", c:"没什么", g:6, t:"下", u:"Unit 4 Then and now" },
  { e:"thought", c:"想(过去式)", g:6, t:"下", u:"Unit 4 Then and now" },
  { e:"felt", c:"感觉(过去式)", g:6, t:"下", u:"Unit 4 Then and now" },
  { e:"dream", c:"梦", g:6, t:"下", u:"Unit 4 Then and now" },
  { e:"woke", c:"醒来(过去式)", g:6, t:"下", u:"Unit 4 Then and now" },
];

// 去重（按英文）
const seen = new Set();
const PEP_VOCABULARY_UNIQUE = PEP_VOCABULARY.filter(w => {
  const key = w.e.toLowerCase();
  if (seen.has(key)) return false;
  seen.add(key);
  return true;
});

// 按年级获取单词
function getWordsByGrade(grade) {
  return PEP_VOCABULARY_UNIQUE.filter(w => w.g === grade);
}

// 按年级+单元获取单词
function getWordsByUnit(grade, term, unit) {
  return PEP_VOCABULARY.filter(w => w.g === grade && w.t === term && w.u === unit);
}

// 获取某年级所有单元列表
function getUnitsByGrade(grade, term) {
  const units = new Set();
  PEP_VOCABULARY.filter(w => w.g === grade && w.t === term).forEach(w => units.add(w.u));
  return [...units];
}

console.log(`✅ 人教版PEP词库已加载：${PEP_VOCABULARY_UNIQUE.length} 个不重复单词（原始${PEP_VOCABULARY.length}条）`);
